### ISSUE TITLE
수정사항을 발견해서 전달드립니다.

### ISSUE THREAD

**Issue by ChoiSukwoo** [d2n0s4ur/chzzk-chat#6]
101번쨰/102번쨰 줄 data.bdy[0] 부분 msg 로 수정해야 할듯합니다.
101 번쨰 줄 messageTypeCode = msg.msgTypeCode; 으로 수정해야합니다. 파싱값 확인하니 변수명이 달라용

**Comment by d2n0s4ur** [comment]
제보 감사합니다!
